Adding the Requirements doc to repo
oss-slu/Step_Time_Biofeedback pull request #12
Opened 2024-09-11 21:38 UTC by JackMcPhillips1543

- Installed the required dependencies
- Saved dependencies to a .txt file for users to download
- Closes Issue #8

2024-09-16 22:35 UTC, colinseper commented on backend/requirements.txt
> +aiohttp==3.9.1
Tried running the commands on my local machine with a Virtual Enviornment and had less dependencies in my requirements.txt file (using pip install -r requirements.txt failed). When I did a pip freeze these were the requirements I got were in the attached requirements file. 
[requirements.txt](https://github.com/user-attachments/files/17020836/requirements.txt)

2024-09-16 22:36 UTC, colinseper requested changes
Tried running the commands on my local machine with a Virtual Enviornment and had less dependencies in my requirements.txt file (using pip install -r requirements.txt failed). When I did a pip freeze these were the requirements I got were in the attached requirements file. 
[requirements.txt](https://github.com/user-attachments/files/17020836/requirements.txt)

Additionally, the README is missing instructions on installing dependencies.
Task #8: Add instructions in the README on how to install dependencies (pip install -r requirements.txt)

2024-09-17 00:10 UTC, JackMcPhillips1543 commented
> Tried running the commands on my local machine with a Virtual Enviornment and had less dependencies in my requirements.txt file (using pip install -r requirements.txt failed). When I did a pip freeze these were the requirements I got were in the attached requirements file. [requirements.txt](https://github.com/user-attachments/files/17020836/requirements.txt)
> 
> Additionally, the README is missing instructions on installing dependencies. Task #8: Add instructions in the README on how to install dependencies (pip install -r requirements.txt)

I fixed the read me, can you try to run it again once you cd into the backend folder

2024-09-17 15:42 UTC, kate-holdener commented
> * Installed the required dependencies:
> * Saved dependencies to a .txt file for users to download
> * Closes Issue [Install and Document Required Python Libraries #8](https://github.com/oss-slu/Step_Time_Biofeedback/issues/8)
> 
> All of these changes were required because the repo was empty and we needed to get all the requirements

@JackMcPhillips1543 Please use:
Fixes #8 
At the top of the PR (do this for future PRs too)

2024-09-17 15:44 UTC, kate-holdener commented on README.md
It would be also good to specify instructions for creating a virtual environment in python

2024-09-18 03:19 UTC, git-voo requested changes
Good job @JackMcPhillips1543! Your branch name and commit message follow our accepted standard. I like that.  I have just a few things for you to note and/or correct.

1. I see about 59 dependencies in your requirements.txt, we don't need all of this yet, right? we will install them as we go let's not crowd the list with redundant dependencies. Work with @Nissa9902 and @colinseper to learn of the dependencies they made use of and restrict your list to just those.
2. For future pull requests, only contributions that directly modify the codebase will be considered for merging into the main branch. An exception will be made for this PR because the requirement for code-based contributions was not communicated by me early enough.
3. Remember to always add me as a reviewer to your PRs. By doing this, I will get a notification that facilitates how promptly you get feedback.
Always assign the PR to yourself for the same reason as above. It helps us keep track, know who to reach out to for what, get notified promptly, and maintain professionalism.

2024-09-20 03:33 UTC, colinseper submitted a review, later dismissed
The updates all look good on my end, nice job!

2024-09-22 17:59 UTC, git-voo submitted a review, later dismissed
Good. we can work this this

2024-09-23 14:27 UTC, git-voo approved these changes

2024-09-23 14:27 UTC, merged