Implemented Python script to connect to QTM via LSL and log data
oss-slu/Step_Time_Biofeedback pull request #14
Opened 2024-09-15 20:16 UTC by Nissa9902

### Summary

This pull request addresses issue #<issue_number> by implementing a Python script to connect to QTM via LSL and log incoming data.

### Changes Made

- Added `connect_to_qtm.py` script that utilizes `pylsl` to connect to the Lab Streaming Layer (LSL).
- The script resolves a 'Force' stream, pulls samples, and logs them with timestamps.

### Why This Change Is Needed

The new script is essential for logging and analyzing data streams from QTM, which is a key component of our project's data processing pipeline.

### Additional Notes

Please ensure that the LSL library is correctly installed and accessible to run this script successfully.

2024-09-15 20:51 UTC, Nissa9902 commented
fixes issue #9

2024-09-16 22:18 UTC, JackMcPhillips1543 commented on backend/connect_to_qtm.py
Remove some the comments, some of them are repetitive

2024-09-16 22:20 UTC, JackMcPhillips1543 commented
Also please add a README.md that explains how to download the proper requirements for Windows and Mac. For Mac the command is <code>brew install labstreaminglayer/tap/lsl</code>

2024-09-16 22:23 UTC, JackMcPhillips1543 commented
Also add .gitignore please

2024-09-17 16:28 UTC, git-voo commented
Nice job @Nissa9902 !!
Just a few changes and we're good to go.

**About the Commit/Pull Request**
Your branch name and commit message look great. I like it.
1. Remember to always add me as a reviewer to your PRs. By doing this, I will get a notification that facilitates how promptly you get feedback.
2. Always assign the PR to yourself for the same reason as above. It helps us keep track, know who to reach out to for what, get notified promptly, and maintain professionalism.

**About the Code**
The code generally looks good. Seeing that we place so much value on clean codes and reusability, I'd ask you to group your streaming logic into a function.

See sample below:
`
def stream_data(stream_type='Force', sleep_time=0.1):
    """
    Connect to the specified data stream and print the data.

    :param stream_type: Type of the stream to connect to.
    :param sleep_time: Time in seconds to wait between pulling samples.
    """
`
 
You will see the importance of this modular approach better when we start streaming data to the frontend using websockets or APIs

2024-09-17 16:30 UTC, git-voo requested changes
Nice job @Nissa9902 !!
Just a few changes and we're good to go.

**About the Commit/Pull Request**
Your branch name and commit message look great. I like it.
1. Remember to always add me as a reviewer to your PRs. By doing this, I will get a notification that facilitates how promptly you get feedback.
2. Always assign the PR to yourself for the same reason as above. It helps us keep track, know who to reach out to for what, get notified promptly, and maintain professionalism.

**About the Code**
The code generally looks good. Seeing that we place so much value on clean codes and reusability, I'd ask you to group your streaming logic into a function.

See sample below:
````
def stream_data(stream_type='Force', sleep_time=0.1):
    """
    Connect to the specified data stream and print the data.

    :param stream_type: Type of the stream to connect to.
    :param sleep_time: Time in seconds to wait between pulling samples.
    """
``` 
 
You will see the importance of this modular approach better when we start streaming data to the frontend using websockets or APIs

2024-09-22 22:39 UTC, git-voo approved these changes
Nice work!
Let's get this through.

2024-09-22 22:39 UTC, git-voo commented on backend/connect_to_qtm.py
> +    stream_data()
Just a note
Following our modular approach, in the future, stream_data() will be called from a separate component, a central component but I can understand why this is here for testing.

2024-09-23 13:19 UTC, git-voo approved these changes

2024-09-23 13:20 UTC, merged