Added Paramaterization to Step Time Calculation Function
oss-slu/Step_Time_Biofeedback pull request #36
Opened 2024-10-14 03:55 UTC by colinseper

Fixes #32 

What was changed:
- Added functionality to allow non-default threshold and moving average factor values to calculate step time and step time moving averages.
- Added testing to check that the new functionality for threshold and a moving average factor works as intended.

Why it was changed:
- The threshold and moving average factors were changed from constant values to allow researchers to calculate step times and moving averages based on a new threshold and moving average factor respectively.
- Testing was added to ensure the new functionality works as intended and to create a fail-safe for future changes that could break the intended functionality.

How it was changed:
- Updated the step_time_calculation function to take a new moving_avg_factor parameter with a default of 2. 
- Updated the step_time_moving_average calculation to compare against a moving average factor instead of a constant value.
- Updated the step_time_calculation function to return early if the moving_avg_factor was below 2.
- Updated the test_step_time module to test for non-default values for threshold and moving average factor and ensure the proper output is returned.

2024-10-14 03:57 UTC, colinseper commented
@git-voo I just want to follow up that this PR is just based on the requirements in the issue and not the discussion ongoing in the slack. Additionally the question was regarding the need for the moving_avg_factor and step_time_moving_averages in the step_time_calculation function.

2024-10-14 23:44 UTC, JackMcPhillips1543 approved these changes
LGTM all tests pass!

2024-10-17 17:56 UTC, git-voo requested changes

2024-10-21 20:43 UTC, git-voo approved these changes
You did good, Collin!
Well-done.

2024-10-21 20:43 UTC, git-voo commented on backend/test_step_time.py
> +            (1.2, 40), (1.3, 45), (1.4, 50), (1.5, 0), # 0.2
Shouldn't this be 0.3? sif it starts at 1.2 and ends at 1.5 when force_y = 0, 1.5-1.2= 0.3. Maybe I'm missing something, I'm not sure. Please shed some let when you get the chance.

2024-10-21 20:43 UTC, merged