Feature/stream step time data
oss-slu/Step_Time_Biofeedback pull request #44
Opened 2024-10-27 23:16 UTC by Nissa9902

Fixes #41 

### What was changed:
This pull request implements a data streaming mechanism from the `tied belt OSS_f_1.tsv` file, allowing for dynamic calculation of step times based on incoming force data. The changes ensure that the application can handle larger datasets and provide accurate step time calculations.

### Why was it changed:
The modifications were necessary to improve the functionality of the step time calculation feature by enabling real-time data processing. 

### How was it changed:
- Introduced asynchronous data loading from the `.tsv` file to handle streaming input efficiently.
- Implemented logic to check whether the force data exceeds a specified threshold before calculating step times.
- Added functionality to estimate target zones based on the calculated step times and send the results via a WebSocket connection.
- Ensured that the system can process both high and low force values for a comprehensive analysis of the data.

2024-10-28 16:31 UTC, colinseper commented on backend/target_zone_estimation.py
> +async def load_data_from_file(file_path):
add a break between the function and the print statement above

2024-10-28 16:47 UTC, colinseper commented on backend/target_zone_estimation.py
> +            if line.startswith("SAMPLE") or line.strip() == "":
I took a look at a sample .tsv and the files start with NO_OF_SAMPLES, FREQUENCY, TIMESTAMP etc. and other lines similar to this before the line outlining the sample data format (specifically the line that starts like: SAMPLE 
   TIME   FORCE_X,...) you handle with the if statement. I'm not sure you handle this case here.

2024-10-28 17:05 UTC, colinseper commented on backend/test_step_time.py
> +        step_times = calculate_step_time(real_force_data, THRESHOLD)
You can just do calculate_step_time(real_force_data) here since the threshold is 20 by default.

2024-10-28 17:08 UTC, colinseper commented on backend/test_step_time.py
>  if __name__ == '__main__':
I believe this should be removed when this is merged to main.

2024-10-28 17:10 UTC, colinseper commented on backend/test_step_time.py
> +        real_force_data = []
Did you mean to use the load_data_from_file function here? The code seems similar except this code would solve the issue in your load_data_from_file function by checking the length of parts (my comment in target_zone_estimation.py on line 41).

2024-10-28 17:19 UTC, colinseper commented on backend/test_step_time.py
> +        step_times = calculate_step_time(real_force_data, THRESHOLD)
May also want to update this for similar tests in the file.

2024-10-28 17:46 UTC, colinseper requested changes
Overall good job! Just some minor edits/clarifications.

2024-10-30 14:22 UTC, kate-holdener commented on backend/tied belt OSS_f_1.tsv
@Nissa9902 Did you mean to commit this file?

2024-10-31 17:42 UTC, git-voo commented on backend/test_step_time.py
> +        real_force_data = asyncio.run(self.async_load_data_from_file())
`asyncio `is not defined. This is making some tests fail

2024-10-31 17:45 UTC, git-voo commented on backend/test_step_time.py
> +DATA_FILE_PATH = os.path.join(os.path.dirname(__file__), "tied belt OSS_f_1.tsv")
Can we rename this file such that the name has no white space? Use `_` to replace whitespaces

2024-10-31 17:46 UTC, git-voo commented on backend/test_step_time.py
> -        step_times = calculate_step_time(force_data, THRESHOLD)
I agree with you on this. `calculate_step_time` already defaults threshold to 20 so there's no point sending threshold if threshold is 20

2024-10-31 18:11 UTC, Nissa9902 commented on backend/tied belt OSS_f_1.tsv
yes! It contains sample data from the client we would like to stream.

2024-10-31 18:17 UTC, colinseper submitted a review, later dismissed
All good on my end, just need to wait for the merge to pass the new checks.

2024-11-03 20:10 UTC, git-voo approved these changes
Great job @Nissa9902. I nlove how you used `yield` to generate tuples from file rather than `return`. this is an efficient solution.
I added `async`  here `async for force_data in load_data_from_file(data_file_path)` because the loader is async and the app would break without mentioning it where `load_data_from_file` is called. it'd simply be an attempt to iterate over a Promise which is impossible so we have to wait for it to be resolved first.
Please refer to the code for details.
Good job!

2024-11-03 20:10 UTC, merged